import './globals.css'
import type { Metadata } from 'next'
import { Header } from '@/components/general/Header'
import { Footer } from '@/components/general/Footer'
import { ContextProvider } from '@/app/ContextProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen bg-gray-100">
        <ContextProvider>
          <Header />
          <div className="flex-1 mx-auto container px-4 py-2 flex flex-col">
            {children}
          </div>
          <Footer />
        </ContextProvider>
      </body>
    </html>
  )
}
